### ISSUE TITLE
[Suggestion] (Omni)hoppers with filter

### ISSUE THREAD

**Issue by vico93** [enjarai/OmniHopper#11]
First of all, i want to say your mod is incredible and very hand not only in early-game but in late as well!

Well, after playing for a while I realized that i've already had @pcal43's Copper Hopper on my modpack, and due to the clearly conflict (two cooper hoppers would make things confusing), i decided to remove that in favour of Omnihopper.

But the idea of a filtered hopper is interesting, so why not implement on your mod as well? Maybe combining an existing hopper with an iron bar?

**Comment by enjarai** [comment]
My concept for this mod is to stay close to vanilla mechanics and logic while twisting them in interesting and unique ways. A one-block filtered hopper has been done many times before, and does not really fit into that concept, so I have little interest in adding it. A similar thing can also already be achieved using omnihoppers and vanilla redstone logic.
