### ISSUE TITLE
[Suggestion] Config file for modifying transfer speed

### ISSUE THREAD

**Issue by Skitnicki** [enjarai/OmniHopper#13]
Omnihopper is absolutely something that should be something in the base game, so I want to thank you for creating such a useful mod! But one thing I feel is missing and would great to have is a dedicated config file that allows the end user to modify the transfer cooldown (in ticks) for each different hopper added by the mod, or at least the main omnihopper, as well as input/output count every time the cooldown resets. I would even suggest making a compat between OmniHopper and Easy Hopper which adds this capability to vanilla hoppers.

**Comment by enjarai** [comment]
This is currently beyond the scope of this mod. If Easy Hopper wants to make compat from their side though, I'd be happy to facilitate it.
