### ISSUE TITLE
Backport support for more recent changes?

### ISSUE THREAD

**Issue by PlayfulPiano** [enjarai/OmniHopper#16]
Hey there, I just found out about omnihoppers, and I was planning to add it to my 1.18.2 fabric playthrough. But I've noticed that a lot of the features advertised aren't actually within the 1.18.2 version, as they were added for more recent minecraft versions.
Would it be possible to have at least the new additions in 2.0 to be backported for 1.18.2 fabric? Thanks!

**Comment by enjarai** [comment]
Bit late perchance, but I don't plan to do any backports of newer features. It's enough of a hassle to keep up with updates as is.
