### ISSUE TITLE
Can't no longer pull buckets out of furnaces

### ISSUE THREAD

**Issue by travismlee** [enjarai/OmniHopper#19]
In Vanilla 1.20.4, you can pull a bucket out of a furnace with a hopper below it. After installing this mod it seems that functionality was removed.

**Comment by enjarai** [comment]
This is intentional. This mod removes that vanilla inconsistency because it:
1. Allows you to pull from the side of blocks using omnihoppers, and more importantly,
2. Adds a mechanic to let Floppers (The copper fluid hoppers) fill buckets in furnaces directly.

**Comment by purejosh** [comment]
I just spent a few hours trying to find the source of this bug, only to find out that it's intentional. Please consider adding a config for this behavior to be removed.
