### ISSUE TITLE
mod stops hoppers from removing empty buckets from fuel slot in furnace-type stations

### ISSUE THREAD

**Issue by schmitzrj** [enjarai/OmniHopper#23]
I love this mod, but I have to stop using it until this bug is fixed because it breaks my perpetually-fueled furnaces. I've narrowed it down to this mod by elimination. When this mod is enabled in Minecraft 1.20.6 (with Fabric), the hopper will pull the furnace output but won't pull empty buckets (previously filled with lava) from the fuel slot like in vanilla. Please fix. I would love to use this mod again because of how much time and space it saves building machines!

**Comment by enjarai** [comment]
I've added a gamerule for this behaviour as of 2.3.1.
