### ISSUE TITLE
[Request] Chute-like block

### ISSUE THREAD

**Issue by vico93** [enjarai/OmniHopper#29]
What about adding a block similar to Quark's chute to the mod? Since it's tangentially on the same aspect of the game (item transportation).

![image](https://github.com/user-attachments/assets/11f117b2-2bcf-4fc2-9a0b-70229583d984)

**Comment by enjarai** [comment]
This mod basically already has this in the form of the lidless chest:

![lidless](https://github.com/user-attachments/assets/0386c732-537e-47e0-93dc-b80371cbef6a)

I hope that's what you're looking for.
