### ISSUE TITLE
Fluid Hopper will not take from cauldrons

### ISSUE THREAD

**Issue by Helioux** [enjarai/OmniHopper#3]
steps to recreate:

1. place cauldron connected by fluid hopper in any configuration (including omnidirectional) to another cauldron
2. the fluid will not move.

the problem, from some testing with other mods, only seems to effect drawing fluids out of cauldrons.

**Comment by enjarai** [comment]
Fixed in 1.1.2, the issue was that the hopper tries to extract 1/4ths of a bucket at once, but cauldrons only support 1/3rd increments. 

The hopper will now check if the block it's interacting with is a cauldron, and increase the amount extracted when needed.
