### ISSUE TITLE
Add support for expanded storage mod

### ISSUE THREAD

**Issue by ChristopherHaws** [enjarai/OmniHopper#7]
Hey there! Any chance you can add support for [expanded storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage) mod? RIght now the game crashes when I try and use an omni-hopper with an expanded storage chest.

Thanks!

**Comment by enjarai** [comment]
Can you provide logs and a crash report? It seems like expanded storage is closed source, which may make it hard for me to determine the issue.

**Comment by ChristopherHaws** [comment]
Sure!

Logs: https://mclo.gs/SIjdZvM
Crash Report: https://mclo.gs/pszSoQU

Let me know if you need anything else.

**Comment by enjarai** [comment]
From what I can tell, this is an incorrect implementation of the Fabric Transfer API on expanded storage's side. Does using some other item pipe crash the game as well? Either way I suggest opening an issue on their issue tracker. 

As this probably isn't in my power to fix, I'll close this issue for now. Feel free to reopen if ES's dev needs something from my side.

**Comment by ChristopherHaws** [comment]
Thanks for your help, they were able to fix the issue on their end. :)
